version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 99
  reviewers:
    - dominic schwarz
  assignees:
    - dominic schwarz
  labels:
    - dependencies
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
