[[redirects]]
  from = "/line-up"
  to = "/line-up/bands"
  force = true

[[plugins]]
package = "netlify-plugin-subfont"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  changeFreq = "daily"
  priority = 0.5
  # Append missing trailing slash to pretty URL
  trailingSlash = true
  exclude = [
    # './dist/200.html',
    '**/line-up/index.html',
    '**/**/200.html'
  ]
