[build]
  # https://www.netlify.com/blog/2020/04/27/ignore-unnecessary-builds-to-optimize-your-build-times/
  ignore = "git log -1 --pretty=%B | grep dependabot"
  functions = "functions/"

[dev]
  autoLaunch = false

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  changeFreq = "daily"
  priority = 0.5
  # Append missing trailing slash to pretty URL
  trailingSlash = true
  exclude = [
    # './dist/200.html',
    '**/historie/index.html',
    '**/line-up/index.html',
    '**/infos/index.html',
    '**/rechtliches/index.html',
    '**/**/200.html',
    '**/**/404.html'
  ]
