[[redirects]]
  from = "/line-up"
  to = "/line-up/bands"
  force = true

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  changeFreq = "daily"
  priority = 0.5
  # Append missing trailing slash to pretty URL
  trailingSlash = true
  exclude = [
    './200',
    './line-up/index.html',
    # By Glob pattern
    '**/**/child-one.html'
  ]
